CONFIG_ZMK_SPLIT=n

# 🔴 apagar completamente physical layouts
CONFIG_ZMK_PHYSICAL_LAYOUTS=n
CONFIG_ZMK_PHYSICAL_LAYOUTS_DEFAULT=n
CONFIG_ZMK_KEYMAP_ENABLE_PHYSICAL_LAYOUTS=n
CONFIG_ZMK_KEYMAP_ENABLE_HARDWARE_ENCLOSURE=n
